import Foundation

extension SweaterCollection {
    static let builtIn: [SweaterAppRule] = [
        SweaterAppRule(match: "Finder", color: 0xff258de0, chart: "atelier-finder"),
        SweaterAppRule(match: "Microsoft Teams", color: 0xff9283c1, chart: "atelier-teams"),
        SweaterAppRule(match: "MSTeams", color: 0xff9283c1, chart: "atelier-teams"),
        SweaterAppRule(match: "Teams", color: 0xff9283c1, chart: "atelier-teams"),
        SweaterAppRule(match: "Claude", color: 0xffd58561, chart: "atelier-claude"),
        SweaterAppRule(match: "Codex", color: 0xff0a84ff, chart: "atelier-chatgpt"),
        SweaterAppRule(match: "Spotify", color: 0xff497641, chart: "atelier-spotify"),
        SweaterAppRule(match: "Notion", color: 0xfff5f5f2, chart: "atelier-notion"),
        SweaterAppRule(match: "WhatsApp", color: 0xff6ea77b, chart: "atelier-whatsapp"),
        SweaterAppRule(match: "Figma", color: 0xffad7197, chart: "atelier-figma"),
        SweaterAppRule(match: "Google Chrome", color: 0xfff4f0e6, chart: "atelier-chrome"),
        SweaterAppRule(match: "Chrome", color: 0xfff4f0e6, chart: "atelier-chrome"),
        SweaterAppRule(match: "Paper", color: 0xff83ade8, chart: "atelier-paper"),
        SweaterAppRule(match: "Chromium", color: 0xfff4f0e6, chart: "atelier-chrome"),
        SweaterAppRule(match: "Safari", color: 0xff268ed8, chart: "atelier-safari"),
        SweaterAppRule(match: "Firefox", color: 0xff643a9a, chart: "atelier-firefox"),
        SweaterAppRule(match: "Cursor", color: 0xff26251e, chart: "atelier-cursor"),
        SweaterAppRule(match: "Slack", color: 0xff542a52, chart: "atelier-slack"),
        SweaterAppRule(match: "zoom.us", color: 0xff2877eb, chart: "atelier-zoom"),
        SweaterAppRule(match: "Zoom", color: 0xff2877eb, chart: "atelier-zoom"),
        SweaterAppRule(match: "Telegram", color: 0xff389ece, chart: "atelier-telegram"),
        SweaterAppRule(match: "Messages", color: 0xff55af51, chart: "atelier-messages"),
        SweaterAppRule(match: "Mail", color: 0xff2986ce, chart: "atelier-mail"),
        SweaterAppRule(match: "Notes", color: 0xfff6f0d9, chart: "atelier-notes"),
        SweaterAppRule(match: "Calendar", color: 0xfff7f3e9, chart: "atelier-calendar"),
        SweaterAppRule(match: "Reminders", color: 0xfff6f3eb, chart: "atelier-reminders"),
        SweaterAppRule(match: "Music", color: 0xffe64e70, chart: "atelier-music"),
        SweaterAppRule(match: "Apple Music", color: 0xffe64e70, chart: "atelier-music"),
        SweaterAppRule(match: "Photos", color: 0xfff8f0db, chart: "atelier-photos"),
        SweaterAppRule(match: "Preview", color: 0xff597baf, chart: "atelier-preview"),
        SweaterAppRule(match: "Microsoft Word", color: 0xff2855a1, chart: "atelier-word"),
        SweaterAppRule(match: "Microsoft Excel", color: 0xff28674f, chart: "atelier-excel"),
        SweaterAppRule(
            match: "Microsoft PowerPoint", color: 0xffb9573d, chart: "atelier-powerpoint"),
        SweaterAppRule(match: "Microsoft Outlook", color: 0xff176bb7, chart: "atelier-outlook"),
        SweaterAppRule(match: "Code", color: 0xff237caf, chart: "atelier-vscode"),
        SweaterAppRule(match: "Visual Studio Code", color: 0xff237caf, chart: "atelier-vscode"),
        SweaterAppRule(match: "Adobe Photoshop", color: 0xff182f45, chart: "atelier-photoshop"),
        SweaterAppRule(match: "Adobe Illustrator", color: 0xff4e3029, chart: "atelier-illustrator"),
        SweaterAppRule(match: "ChatGPT", color: 0xff0a84ff, chart: "atelier-chatgpt"),
        SweaterAppRule(match: "Grok Bot", color: 0xff34383b, chart: "atelier-grok"),
        SweaterAppRule(match: "Discord", color: 0xff5865f2, chart: "checker"),
        SweaterAppRule(match: "Granola", color: 0xff292e2a, chart: "atelier-granola"),
        SweaterAppRule(match: "Terminal", color: 0xff303c35, chart: "atelier-terminal"),
        SweaterAppRule(match: "ghostty", color: 0xff2b3350, chart: "atelier-ghostty"),
    ]
}
