import Foundation

public enum ClipboardPasteboardFilter {
    public static let concealedType = "org.nspasteboard.ConcealedType"
    public static let transientType = "org.nspasteboard.TransientType"
    public static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"
    public static let edithOwnTag = "com.pulkit.edith.clipboard.own"

    public static let knownTransientTypes: Set<String> = [
        "Pasteboard generator type",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
    ]

    public static func shouldSkip(types: [String]) -> Bool {
        let set = Set(types)
        return set.contains(edithOwnTag) || set.contains(concealedType)
            || set.contains(transientType) || set.contains(autoGeneratedType)
            || !set.isDisjoint(with: knownTransientTypes)
    }

    public static func capturableTypes(from types: [String]) -> [String] {
        types.filter { !$0.hasPrefix("dyn.") }
    }
}
