import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../site-chrome";

export const metadata: Metadata = {
  title: "Privacy Policy · Edith",
  description:
    "Edith's privacy policy. Local-first by design: no accounts, no usage telemetry, your product data stays on your Mac.",
  alternates: {
    canonical: "/privacy",
  },
};

export default function PrivacyPage() {
  return (
    <>
      <SiteHeader />
      <main className="mx-auto max-w-190 px-6 pt-35 pb-24 [&>h1]:mb-2! [&>h1]:text-[clamp(2rem,5vw,2.8rem)]! [&>h1]:tracking-[-0.02em]! [&>h2]:mt-10! [&>h2]:mb-3! [&>h2]:text-[20px]! [&>p]:mb-3 [&>p]:text-muted [&>p]:leading-[1.7] [&>ul]:mb-4 [&>ul]:list-disc [&>ul]:pl-5.5 [&_a]:text-accent [&_li]:mb-3 [&_li]:text-muted [&_li]:leading-[1.7]">
        <h1>Privacy Policy</h1>
        <p className="mb-10! text-[0.9rem]! text-subtle!">Last updated: July 19, 2026</p>

        <p>
          Edith is built local-first. The short version: the app has no
          accounts, collects no usage telemetry, and your product data stays on
          your Mac unless you explicitly turn on iCloud backup, which stores it
          in your own iCloud Drive. The only data we process is the minimum
          needed to sell and activate licenses, described below.
        </p>

        <h2>What the app stores, and where</h2>
        <ul>
          <li>
            Usage analytics (tokens, costs, rate-limit history) are computed on
            your Mac from local files that your AI tools already write, and are
            stored in the app&apos;s local data folder.
          </li>
          <li>
            Clipboard history, shelf files, music, and settings are stored
            locally on your Mac.
          </li>
          <li>
            None of the above is transmitted to us. We run no servers that
            receive, process, or store your usage data; our servers handle only
            licensing and downloads.
          </li>
        </ul>

        <h2>Rate-limit checks</h2>
        <p>
          To show live session and weekly limits, the app queries your AI
          provider&apos;s API directly from your Mac using credentials already
          on your machine. Those requests go from you to your provider. Edith
          never sees them.
        </p>

        <h2>Optional iCloud backup</h2>
        <p>
          If you enable iCloud backup, the app copies selected data (settings,
          usage history, music, clipboard history, at your choice) into your own
          iCloud Drive so it can merge across your Macs. That data is governed
          by your Apple account and Apple&apos;s privacy terms. Turn the toggle
          off and the app stops syncing.
        </p>

        <h2>No accounts, no telemetry</h2>
        <ul>
          <li>No sign-up, login, or account of any kind.</li>
          <li>
            No analytics SDKs, crash reporters, or tracking pixels inside the
            app.
          </li>
          <li>
            No advertising, and your product data is never sold or shared,
            because it never leaves your Mac.
          </li>
        </ul>

        <h2>Licensing and activation data</h2>
        <p>
          Activating and verifying a license requires a small licensing service
          that we operate. It stores, per license and device:
        </p>
        <ul>
          <li>
            A one-way digest of your license key plus its last four characters
            (for support). The full key is never stored or logged.
          </li>
          <li>
            A random device identifier and a device public key generated by the
            app. No hostname or hardware serial number is collected in the
            current protocol version. Devices first activated with an older
            app version may retain a one-way hash of the previous hardware
            identifier until the device is deactivated.
          </li>
          <li>An optional device name you choose, shown in your device list.</li>
          <li>Activation and verification timestamps, and the app version.</li>
          <li>Your plan and entitlement records.</li>
          <li>
            Payment references (such as an order id and email address) from our
            payment provider, never card details.
          </li>
          <li>
            Standard hosting provider request logs, including IP addresses,
            kept for a short period.
          </li>
        </ul>
        <p>
          This data is used only to enforce your plan&apos;s device allowance,
          prevent fraud, and provide support. Device records are kept until you
          deactivate the device, plus a bounded audit window; security events
          are kept for 12 months; payment records are kept as long as legal and
          accounting requirements demand. To remove a device, use Settings in
          the app; for deletion requests or anything else, email{" "}
          <a href="mailto:support@edith.app">support@edith.app</a>.
        </p>

        <h2>This website</h2>
        <p>
          edith.app is a static site. Our hosting provider keeps standard,
          short-lived server logs (such as IP address and requested page) to
          operate the service. The site sets no tracking cookies.
        </p>

        <h2>Payments</h2>
        <p>
          Purchases are handled by our payment processor. We receive the
          information needed to deliver your license (such as your email address
          and order reference), never your card details.
        </p>

        <h2>Changes</h2>
        <p>
          If this policy changes, the new version will be posted here with an
          updated date. Material changes will be noted in the app&apos;s release
          notes.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about privacy? Email{" "}
          <a href="mailto:support@edith.app">support@edith.app</a>.
        </p>
      </main>
      <SiteFooter />
    </>
  );
}
