import Testing

@testable import EdithKit

@Suite struct ClipboardPasteboardFilterTests {
    @Test func concealedTypeIsSkipped() {
        #expect(
            ClipboardPasteboardFilter.shouldSkip(
                types: ["public.utf8-plain-text", ClipboardPasteboardFilter.concealedType]))
    }

    @Test func transientTypeIsSkipped() {
        #expect(
            ClipboardPasteboardFilter.shouldSkip(
                types: [ClipboardPasteboardFilter.transientType]))
    }

    @Test func autoGeneratedTypeIsSkipped() {
        #expect(
            ClipboardPasteboardFilter.shouldSkip(
                types: [ClipboardPasteboardFilter.autoGeneratedType]))
    }

    @Test func edithOwnTagIsSkipped() {
        #expect(
            ClipboardPasteboardFilter.shouldSkip(types: [ClipboardPasteboardFilter.edithOwnTag]))
    }

    @Test func plainTextIsNotSkipped() {
        #expect(!ClipboardPasteboardFilter.shouldSkip(types: ["public.utf8-plain-text"]))
    }

    @Test func knownTransientTypesAreSkipped() {
        for type in ClipboardPasteboardFilter.knownTransientTypes {
            #expect(ClipboardPasteboardFilter.shouldSkip(types: ["public.utf8-plain-text", type]))
        }
    }

    @Test func capturableTypesDropsDynPrefixed() {
        let filtered = ClipboardPasteboardFilter.capturableTypes(
            from: ["public.utf8-plain-text", "dyn.ah62d4rv4gu8yc6durvwwa3xmrvw1um1"])
        #expect(filtered == ["public.utf8-plain-text"])
    }
}
