import Foundation
import Testing

@testable import EdithKit

@Suite struct ClipboardCapturePolicyTests {
    private let text = ["public.utf8-plain-text"]

    private func scratch(_ name: String) -> UserDefaults {
        let suite = "test.clipboard.policy.\(name)"
        let defaults = UserDefaults(suiteName: suite)!
        defaults.removePersistentDomain(forName: suite)
        return defaults
    }

    @Test func capturesEverythingByDefault() {
        let defaults = scratch("default")

        #expect(
            ClipboardCapturePolicy.decide(
                types: text, sourceBundleID: "com.apple.Notes", defaults: defaults)
                == .capture(
                    ClipboardCaptureOptions(saveFiles: true, saveImages: true, saveText: true)))
        #expect(!ClipboardCapturePolicy.isPaused(defaults))
    }

    @Test func pauseWinsOverEveryOtherRule() {
        let defaults = scratch("paused")
        defaults.set(true, forKey: AppStorageKeys.Clipboard.capturePaused)

        #expect(ClipboardCapturePolicy.isPaused(defaults))
        #expect(
            ClipboardCapturePolicy.decide(types: text, sourceBundleID: nil, defaults: defaults)
                == .skip(.paused))
        #expect(
            ClipboardCapturePolicy.decide(
                types: [ClipboardPasteboardFilter.concealedType], sourceBundleID: nil,
                defaults: defaults) == .skip(.paused))
    }

    @Test func resumingCapturesAgain() {
        let defaults = scratch("resume")
        defaults.set(true, forKey: AppStorageKeys.Clipboard.capturePaused)
        defaults.set(false, forKey: AppStorageKeys.Clipboard.capturePaused)

        #expect(
            ClipboardCapturePolicy.decide(types: text, sourceBundleID: nil, defaults: defaults)
                != .skip(.paused))
    }

    @Test(arguments: [
        ClipboardPasteboardFilter.concealedType, ClipboardPasteboardFilter.transientType,
        ClipboardPasteboardFilter.autoGeneratedType, ClipboardPasteboardFilter.edithOwnTag,
        "com.agilebits.onepassword",
    ])
    func passwordManagerMarkersAreNeverRecorded(marker: String) {
        let defaults = scratch("private")

        #expect(
            ClipboardCapturePolicy.decide(
                types: text + [marker], sourceBundleID: "com.apple.Safari", defaults: defaults)
                == .skip(.privateContent))
    }

    @Test func knownAndUserIgnoredAppsAreSkipped() {
        let defaults = scratch("ignored")
        defaults.set(
            " com.example.secret , com.other.app", forKey: AppStorageKeys.Clipboard.ignoredApps)

        #expect(
            ClipboardCapturePolicy.decide(
                types: text, sourceBundleID: "com.bitwarden.desktop", defaults: defaults)
                == .skip(.ignoredApp))
        #expect(
            ClipboardCapturePolicy.decide(
                types: text, sourceBundleID: "com.example.secret", defaults: defaults)
                == .skip(.ignoredApp))
        #expect(
            ClipboardCapturePolicy.decide(
                types: text, sourceBundleID: "com.example.public", defaults: defaults)
                != .skip(.ignoredApp))
    }

    @Test func savedTypePreferencesFlowIntoTheCaptureOptions() {
        let defaults = scratch("types")
        defaults.set(false, forKey: AppStorageKeys.Clipboard.saveFiles)
        defaults.set(false, forKey: AppStorageKeys.Clipboard.saveText)

        #expect(
            ClipboardCapturePolicy.decide(types: text, sourceBundleID: nil, defaults: defaults)
                == .capture(
                    ClipboardCaptureOptions(saveFiles: false, saveImages: true, saveText: false)))
    }

    @Test func pickingPastesByDefaultOnceAccessibilityIsGranted() {
        let defaults = scratch("paste")

        #expect(ClipboardCapturePolicy.autoPasteEnabled(defaults))
        #expect(!ClipboardCapturePolicy.pastesOnPick(defaults))

        defaults.set(true, forKey: AppStorageKeys.Permissions.accessibilityGranted)
        #expect(ClipboardCapturePolicy.pastesOnPick(defaults))

        defaults.set(false, forKey: AppStorageKeys.Clipboard.autoPaste)
        #expect(!ClipboardCapturePolicy.autoPasteEnabled(defaults))
        #expect(!ClipboardCapturePolicy.pastesOnPick(defaults))
    }

    @Test func pauseAndAutoPasteAreReachableFromTheCommandLine() {
        let paused = ConfigCatalog.definition(for: AppStorageKeys.Clipboard.capturePaused)
        let paste = ConfigCatalog.definition(for: AppStorageKeys.Clipboard.autoPaste)

        #expect(paused?.fallback == .bool(false))
        #expect(paste?.fallback == .bool(true))
        #expect(SettingsBackup.deviceLocalKeys.contains(AppStorageKeys.Clipboard.capturePaused))
        #expect(!SettingsBackup.backedKeys.contains(AppStorageKeys.Clipboard.capturePaused))
    }
}
