@testable import EdithKit
import Foundation
import Testing

@Suite struct CodeStatsNoiseTests {
    private func header(
        _ sha: String, subject: String = "change", email: String = "p@x.com",
        trailers: String = ""
    ) -> String {
        "C\t\(sha)\t2026-06-01T12:00:00+00:00\tPulkit\t\(email)\t1780315200\t\(trailers)\t\(subject)"
    }

    private func file(
        _ path: String, removed: [String] = [], added: [String] = [], top: Bool = false
    )
        -> String
    {
        let start = top ? 1 : 10
        var lines = [
            "diff --git a/\(path) b/\(path)", "--- a/\(path)", "+++ b/\(path)",
            "@@ -\(start),\(removed.count) +\(start),\(added.count) @@",
        ]
        lines += removed.map { "-" + $0 } + added.map { "+" + $0 }
        return lines.joined(separator: "\n")
    }

    private func parse(_ parts: [String]) -> [CodeStatsCommit] {
        CodeStatsLogParser.parse(
            parts.joined(separator: "\n"), repository: "octo/demo", isMine: { _, _ in true })
    }

    @Test func readsTheTimestampSubjectAndFileCount() {
        let commits = parse([
            header("a1", subject: "Add\tthe parser"), file("a.ts", added: ["x"]),
            file("b.ts", added: ["y"]),
        ])
        #expect(commits[0].timestamp == 1_780_315_200)
        #expect(commits[0].subject == "Add\tthe parser")
        #expect(commits[0].files == 2)
        #expect(commits[0].flags.isEmpty)
    }

    @Test func whitespaceOnlyReformatCountsNoAuthoredLines() {
        let before = (0..<30).map { "let value\($0) = \($0)" }
        let after = before.map { "    " + $0.replacingOccurrences(of: " = ", with: "=") }
        let commits = parse([header("w1"), file("app.swift", removed: before, added: after)])
        let change = commits[0].changes.first
        #expect(change?.raw == CodeStatsLanguageCounts(updated: 30))
        #expect(change?.counts == CodeStatsLanguageCounts())
        #expect(commits[0].totals.authored == 0)
        #expect(commits[0].flags.contains(.formatting))
    }

    @Test func aRealEditInsideAReformatStillCounts() {
        let commits = parse([
            header("w2"),
            file("app.swift", removed: ["a = 1", "b = 2"], added: ["a=1", "b = 3", "c = 4"]),
        ])
        #expect(commits[0].totals == CodeStatsLanguageCounts(added: 1, updated: 1))
        #expect(commits[0].rawTotals == CodeStatsLanguageCounts(added: 1, updated: 2))
        #expect(!commits[0].flags.contains(.formatting))
    }

    @Test func formatterSubjectsAreFlagged() {
        for subject in [
            "format codebase with Biome", "style: run prettier", "chore: format", "Reformat",
            "Run swift format on sources", "lint --fix",
        ] {
            #expect(CodeStatsLogParser.isFormatterSubject(subject), "\(subject)")
        }
        for subject in ["Fix date format parsing", "fix: format dates in the header", "Add form"] {
            #expect(!CodeStatsLogParser.isFormatterSubject(subject), "\(subject)")
        }
        let commits = parse([
            header("f1", subject: "format codebase with Biome"), file("a.ts", added: ["x"]),
        ])
        #expect(commits[0].flags.contains(.formatting))
    }

    @Test func categoriesSeparateCodeMarkupDataDocsAndGenerated() {
        let expected: [String: CodeStatsCategory] = [
            "src/app.ts": .code, "Makefile": .code, "web/index.html": .markup,
            "web/site.scss": .markup, "icon.svg": .markup, "config/app.json": .data,
            "deploy.yaml": .data, "notes/plan.md": .docs, "LICENSE": .docs,
            "src/__snapshots__/view.test.ts.snap": .generated,
            "api/client.generated.ts": .generated, "proto/user.pb.go": .generated,
            "src/generated/schema.ts": .generated, "lib/app.min.css": .generated,
            "package-lock.json": .generated, "user_pb2.py": .generated,
        ]
        for (path, category) in expected {
            #expect(CodeStatsLanguage.category(path) == category, "\(path)")
        }
    }

    @Test func generatedMarkersInTheFirstLinesMarkTheFileGenerated() {
        let commits = parse([
            header("g1"),
            file(
                "src/api.ts", added: ["// Code generated by protoc. DO NOT EDIT.", "x"], top: true),
            file("src/late.ts", added: ["// do not edit"]),
            file("data.json", added: ["{}"]),
        ])
        let byLanguage = Dictionary(
            grouping: commits[0].changes, by: { $0.language + "/" + $0.category.rawValue })
        #expect(byLanguage["TypeScript/generated"]?.first?.raw.added == 2)
        #expect(byLanguage["TypeScript/code"]?.first?.counts.added == 1)
        #expect(byLanguage["JSON/data"]?.first?.counts.added == 1)
        #expect(commits[0].totals.authored == 2)
        #expect(commits[0].languages["TypeScript"]?.added == 1)
    }

    @Test func fingerprintsIgnorePathsFileOrderAndWhitespace() {
        let first = parse([
            header("p1", subject: "Import the app"), file("a.ts", added: ["let a = 1"]),
            file("b.ts", added: ["let b = 2"]),
        ])[0]
        let moved = parse([
            header("p2", subject: "Import the app"),
            file("sub/dir/b.ts", added: ["let  b=2"]), file("sub/dir/a.ts", added: ["let a = 1"]),
        ])[0]
        let otherAuthor = parse([
            header("p3", subject: "Import the app", email: "q@x.com"),
            file("a.ts", added: ["let a = 1"]), file("b.ts", added: ["let b = 2"]),
        ])[0]
        let otherContent = parse([
            header("p4", subject: "Import the app"), file("a.ts", added: ["let a = 9"]),
            file("b.ts", added: ["let b = 2"]),
        ])[0]
        #expect(first.fingerprint != nil)
        #expect(first.fingerprint == moved.fingerprint)
        #expect(first.fingerprint != otherAuthor.fingerprint)
        #expect(first.fingerprint != otherContent.fingerprint)
        let empty = parse([header("p5")])[0]
        #expect(empty.fingerprint == nil)
    }

    @Test func trailersReachTheAttribution() {
        let attribution = CodeStatsAttribution(
            identity: CodeStatsIdentity(emails: ["me@x.com"]), owned: false)
        let text = [
            "C\tc1\t2026-06-01T12:00:00Z\tOther\to@x.com\t1\tMe <me@x.com>\u{1f}Bot <b@x.com>\tPair",
            file("a.ts", added: ["x"]),
            "C\tc2\t2026-06-01T12:00:00Z\tOther\to@x.com\t1\t\tSolo", file("a.ts", added: ["y"]),
        ].joined(separator: "\n")
        let commits = CodeStatsLogParser.parse(text, repository: "a/b") {
            attribution.flags(name: $0, email: $1, coAuthors: $2)
        }
        #expect(commits.map(\.sha) == ["c1"])
        #expect(commits[0].flags == .coAuthored)
    }
}

@Suite struct CodeStatsAttributionTests {
    private let identity = CodeStatsIdentity(substrings: ["octocat"], emails: ["me@x.com"])

    @Test func agentCommitsCountOnlyInOwnedRepositoriesOrWithMyTrailer() {
        let owned = CodeStatsAttribution(identity: identity, owned: true)
        let foreign = CodeStatsAttribution(identity: identity, owned: false)
        let agents: [(String, String)] = [
            ("Claude", "noreply@anthropic.com"), ("Cursor Agent", "cursoragent@cursor.com"),
            ("Copilot", "198982749+Copilot@users.noreply.github.com"),
            ("pukbot[bot]", "1+pukbot[bot]@users.noreply.github.com"),
            ("devin-ai-integration[bot]", "x@devin.ai"), ("Codex", "codex@openai.com"),
        ]
        for (name, email) in agents {
            #expect(
                owned.flags(name: name, email: email, coAuthors: []) == .agentAssisted, "\(name)")
            #expect(foreign.flags(name: name, email: email, coAuthors: []) == nil, "\(name)")
            #expect(
                foreign.flags(name: name, email: email, coAuthors: ["Me <me@x.com>"])
                    == .agentAssisted, "\(name)")
        }
    }

    @Test func automationNeverCountsAndHumansNeedATrailer() {
        let owned = CodeStatsAttribution(identity: identity, owned: true)
        for name in ["dependabot[bot]", "renovate[bot]", "github-actions[bot]", "release-bot[bot]"]
        {
            #expect(
                owned.flags(
                    name: name, email: "x@users.noreply.github.com",
                    coAuthors: [
                        "Me <me@x.com>"
                    ]) == nil, "\(name)")
        }
        #expect(owned.flags(name: "Claude Monet", email: "claude@art.fr", coAuthors: []) == nil)
        #expect(owned.flags(name: "Octocat", email: "old@x.com", coAuthors: []) == [])
        #expect(
            owned.flags(name: "Pal", email: "pal@x.com", coAuthors: ["octocat <o@users.x>"])
                == .coAuthored)
    }

    @Test func extraAgentsAndOwnershipFeedTheRulesFingerprint() {
        let plain = CodeStatsAttribution(identity: identity, owned: true)
        let extra = CodeStatsAttribution(identity: identity, agents: ["Aider"], owned: true)
        #expect(extra.flags(name: "aider", email: "a@x.com", coAuthors: []) == .agentAssisted)
        #expect(plain.flags(name: "aider", email: "a@x.com", coAuthors: []) == nil)
        #expect(plain.fingerprint != extra.fingerprint)
        #expect(
            plain.fingerprint != CodeStatsAttribution(identity: identity, owned: false).fingerprint)
        #expect(CodeStatsAttribution.isOwned("OctoCat/app", logins: ["octocat"]))
        #expect(!CodeStatsAttribution.isOwned("acme/app", logins: ["octocat"]))
        let trailer = CodeStatsAttribution.parseTrailer(" Jane Doe <jane@x.com> ")
        #expect(trailer.name == "Jane Doe")
        #expect(trailer.email == "jane@x.com")
    }
}
