import Foundation

public enum CodeStatsCategory: String, Codable, CaseIterable, Hashable, Sendable {
    case code
    case markup
    case data
    case docs
    case generated

    public static let filterable: [CodeStatsCategory] = [.code, .markup, .data, .docs]
    public static let counted: Set<CodeStatsCategory> = [.code, .markup, .docs]

    public var title: String {
        switch self {
        case .code: "Code"
        case .markup: "Markup and style"
        case .data: "Data and config"
        case .docs: "Docs"
        case .generated: "Generated"
        }
    }
}

public enum CodeStatsLanguage {
    public static let other = "Other"
    public static let rulesVersion = 2

    public static let excludedPathspecs = [
        "**/node_modules/**", "**/dist/**", "**/build/**", "**/vendor/**", "**/.next/**",
        "**/out/**", "**/coverage/**", "**/.turbo/**", "**/*.min.js", "**/*.min.css",
        "**/package-lock.json", "**/yarn.lock", "**/pnpm-lock.yaml", "**/bun.lockb",
        "**/*.lock", "**/go.sum", "**/poetry.lock", "**/composer.lock", "**/Gemfile.lock",
    ].map { ":(exclude,glob)" + $0 }

    private static let lockBasenames: Set<String> = [
        "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb", "cargo.lock",
        "poetry.lock", "composer.lock", "gemfile.lock", "go.sum",
    ]

    private static let generatedSegments: Set<String> = [
        "node_modules", "dist", "build", "vendor", ".next", "out", "coverage", ".turbo",
    ]

    private static let specialBasenames = [
        "dockerfile": "Dockerfile", "makefile": "Makefile", "cmakelists.txt": "CMake",
    ]

    private static let extensions: [String: String] = [
        "ts": "TypeScript", "tsx": "TSX", "js": "JavaScript", "jsx": "JSX",
        "mjs": "JavaScript", "cjs": "JavaScript", "py": "Python", "rb": "Ruby", "go": "Go",
        "rs": "Rust", "java": "Java", "kt": "Kotlin", "swift": "Swift", "c": "C",
        "h": "C/C++ Header", "hpp": "C/C++ Header", "cpp": "C++", "cc": "C++", "cxx": "C++",
        "cs": "C#", "php": "PHP", "scala": "Scala", "dart": "Dart", "lua": "Lua", "r": "R",
        "jl": "Julia", "zig": "Zig", "sh": "Shell", "bash": "Shell", "zsh": "Shell",
        "ps1": "PowerShell", "html": "HTML", "css": "CSS", "scss": "SCSS", "sass": "SCSS",
        "less": "Less", "vue": "Vue", "svelte": "Svelte", "json": "JSON", "yaml": "YAML",
        "yml": "YAML", "toml": "TOML", "xml": "XML", "csv": "CSV", "md": "Markdown",
        "mdx": "MDX", "txt": "Text", "sql": "SQL", "proto": "Protobuf", "graphql": "GraphQL",
        "gql": "GraphQL", "ipynb": "Jupyter Notebook",
    ]

    private static let markupExtensions: Set<String> = [
        "html", "htm", "css", "scss", "sass", "less", "svg",
    ]

    private static let dataExtensions: Set<String> = [
        "json", "jsonc", "json5", "yaml", "yml", "toml", "xml", "csv", "tsv", "lock", "log",
        "ipynb", "plist", "ini", "cfg", "conf", "properties", "env",
    ]

    private static let docsExtensions: Set<String> = ["md", "mdx", "txt", "rst", "adoc"]

    private static let docsBasenames: Set<String> = [
        "license", "readme", "changelog", "authors", "notice", "contributing", "copying",
    ]

    private static let generatedArtifactSegments: Set<String> = ["__snapshots__", "generated"]

    private static let generatedArtifactInfixes = [".generated.", ".pb.", ".min.", ".g."]

    public static let generatedMarkers = [
        "do not edit", "@generated", "auto-generated", "autogenerated", "code generated",
        "generated by",
    ]

    public static func isGeneratedArtifact(_ path: String) -> Bool {
        if isGenerated(path) { return true }
        let segments = path.lowercased().split(separator: "/")
        let base = String(segments.last ?? "")
        if segments.dropLast().contains(where: { generatedArtifactSegments.contains(String($0)) })
        {
            return true
        }
        if base.hasSuffix(".snap") || base.hasSuffix("_pb2.py") { return true }
        return generatedArtifactInfixes.contains { base.contains($0) }
    }

    public static func category(_ path: String) -> CodeStatsCategory {
        if isGeneratedArtifact(path) { return .generated }
        let base = (path.split(separator: "/").last.map(String.init) ?? path).lowercased()
        let stem = base.split(separator: ".").first.map(String.init) ?? base
        guard let dot = base.lastIndex(of: "."), dot != base.startIndex else {
            return docsBasenames.contains(stem) ? .docs : .code
        }
        let suffix = String(base[base.index(after: dot)...])
        if markupExtensions.contains(suffix) { return .markup }
        if dataExtensions.contains(suffix) { return .data }
        if docsExtensions.contains(suffix) || docsBasenames.contains(stem) { return .docs }
        return .code
    }

    public static func hasGeneratedMarker<Line: StringProtocol>(_ line: Line) -> Bool {
        let lowered = line.lowercased()
        return generatedMarkers.contains { lowered.contains($0) }
    }

    public static func isGenerated(_ path: String) -> Bool {
        let segments = path.lowercased().split(separator: "/", omittingEmptySubsequences: false)
        let base = String(segments.last ?? "")
        if lockBasenames.contains(base) { return true }
        if base.hasSuffix(".min.js") || base.hasSuffix(".min.css") { return true }
        return segments.contains { generatedSegments.contains(String($0)) }
    }

    public static func classify(_ path: String) -> String? {
        isGenerated(path) ? nil : language(path)
    }

    public static func language(_ path: String) -> String {
        let base = (path.split(separator: "/").last.map(String.init) ?? path).lowercased()
        if let special = specialBasenames[base] { return special }
        guard let dot = base.lastIndex(of: "."), dot != base.startIndex else { return other }
        return extensions[String(base[base.index(after: dot)...])] ?? other
    }
}
